#!C:\Program Files (x86)\Python38-32\python.exe
print("content-type:text/html\n")
print()
print ("<html>")
print ('<head>')
print ('<title>LOGIN</title>')
print ('</head>')
print ('<body>')
print ('<form method="post" action="well.py"> Username<input type="text" name="nm"><br>')
print ('Password<input type="pasword" name="ps"><br>')
print ('<input type="submit" name="sub"></form>')
print ('</body>')
print ('</html>')